#!/usr/bin/env python

# the main GUI program. Relies on fract4d libs to do the real work

import sys
import os
import struct
import math
import types

import gtk
import gobject

# so we can run without installing.
# FIXME is there a better way?
sys.path.append("..")

from fract4d import fractal,fc,fract4dc

import gtkfractal
import settings
import preferences
import autozoom

# We don't use GDK threads because RedHat seem to compile pygtk
# without thread support. Grrr.
#gtk.gdk.threads_init()

# create global fractal compiler and load standard formula and
# coloring algorithm files
g_comp = fc.Compiler()
g_comp.file_path.append("../fract4d")
g_comp.load_formula_file("gf4d.frm")
g_comp.load_formula_file("gf4d.cfrm")


class MainWindow:
    def __init__(self):
        global g_comp
        self.compiler = g_comp
        self.window = gtk.Window()
        self.window.connect('destroy', self.quit)
        self.window.set_title('Gnofract 4D')

        self.accelgroup = gtk.AccelGroup()
        self.window.add_accel_group(self.accelgroup)
        #self.window.connect('key-press-event', self.on_key_press)
        
        self.vbox = gtk.VBox()
        self.window.add(self.vbox)

        self.create_menu()
        self.create_toolbar()
        self.create_fractal()
        self.create_status_bar()
        
        self.window.show_all()

        self.statuses = [ "Done",
                          "Calculating",
                          "Deepening",
                          "Antialiasing",
                          "Paused" ]
        
    def create_fractal(self):
        window = gtk.ScrolledWindow()
        window.set_policy(gtk.POLICY_AUTOMATIC,gtk.POLICY_AUTOMATIC)
        self.f = gtkfractal.T(self.compiler)
        if len(sys.argv) > 1:
            self.load(sys.argv[1])

        self.f.connect('parameters-changed', self.on_fractal_change)
        
        self.f.draw_image()
        window.set_size_request(640+2,480+2)
        window.add_with_viewport(self.f.widget)
        self.f.connect('progress_changed', self.progress_changed)
        self.f.connect('status_changed',self.status_changed)
        
        self.vbox.pack_start(window)

    def on_fractal_change(self,object):
        print "parameters changed"
        self.f.draw_image()

    def on_key_press(self, event, *args):
        print "key:", event.keyval
        
    def progress_changed(self,f,progress):
        self.bar.set_fraction(progress/100.0)

    def status_changed(self,f,status):
        if status == 2:
            # deepening
            text = "Deepening (%d iterations)" % self.f.maxiter
        else:
            text = self.statuses[status]
            
        self.bar.set_text(text)
        
    def create_menu(self):
        menu_items = (
            ('/_File', None, None, 0, '<Branch>' ),
            ('/File/_Open...', '<control>O', self.open, 0, '<StockItem>', gtk.STOCK_OPEN),
            ('/File/_Save', '<control>S', self.save, 0, '<StockItem>', gtk.STOCK_SAVE),
            ('/File/Save _As...', '<control><shift>S', self.saveas, 0, '<StockItem>', gtk.STOCK_SAVE_AS),
            ('/File/Save _Image', '<control>I', self.save_image, 0, ''),
            ('/File/sep1', None, None, 0, '<Separator>'),
            ('/File/_Quit', '<control>Q', self.quit, 0, '<StockItem>', gtk.STOCK_QUIT),   
            ('/_Edit', None, None, 0, '<Branch>'),
            ('/Edit/_Fractal Settings...','<control>F',self.settings, 0, ''),
            ('/Edit/_Colors...', '<control>L', self.colors, 0, ''),
            ('/Edit/_Preferences...', None, self.preferences, 0, '<StockItem>', gtk.STOCK_PREFERENCES),
            ('/Edit/_Undo', '<control>Z', self.undo, 0, ''),
            ('/Edit/_Redo', '<control>Y', self.redo, 0, ''),
            ('/Edit/R_eset', 'Home', self.reset, 0, '<StockItem>', gtk.STOCK_HOME),
            ('/_Tools', None, None, 0, '<Branch>'),
            ('/_Tools/_Autozoom', '<control>A', self.autozoom, 0, ''),
            ('/_Help', None, None, 0, '<Branch>'),
            ('/_Help/Contents', 'F1', self.contents, 0, ''),
            ('/Help/_About', None, self.about, 0, ''),
            )
    
        item_factory = gtk.ItemFactory(gtk.MenuBar, '<main>', self.accelgroup)
        item_factory.create_items(menu_items)

        menubar = item_factory.get_widget('<main>')

        self.vbox.pack_start(menubar, expand=gtk.FALSE)
        
    def create_status_bar(self):
        self.bar = gtk.ProgressBar()
        self.vbox.pack_end(self.bar, expand=gtk.FALSE)

    def create_toolbar(self):
        self.toolbar = gtk.Toolbar()
        self.toolbar.append_item("preview",None,None,None,None,None)
        self.vbox.pack_start(self.toolbar,expand=gtk.FALSE)
        
    def save(self,action,widget):
        print "save"

    def saveas(self,action,widget):
        print "save as"
    def save_image(self,action,widget):
        fs = gtk.FileSelection("Save Image")
        result = fs.run()
        
        if result == gtk.RESPONSE_OK:
            self.f.save_image(fs.get_filename())
        fs.destroy()

    def settings(self,action,widget):
        settings.show_settings(self.window,self.f)
        
    def colors(self,action,widget):
        print "colors"
        
    def preferences(self,action,widget):
        preferences.show_preferences(self.window, self.f)
        
    def undo(self,action,widget):
        print "undo"
    def redo(self,action,widget):
        print "redo"
    def reset(self,action,widget):
        self.f.reset()

    def autozoom(self,action,widget):
        autozoom.show_autozoom(self.window, self.f)
        
    def contents(self,action,widget):
        print "contents"

    def open(self,action,widget):
        fs = gtk.FileSelection("Open Parameter File")
        result = fs.run()
        
        if result == gtk.RESPONSE_OK:
            self.load(fs.get_filename())
            
        fs.destroy()

    def load(self,file):
        try:
            self.f.loadFctFile(open(file))
            self.f.compile()
        except Exception, err:
            d = gtk.MessageDialog(self.window, gtk.DIALOG_MODAL,
                                  gtk.MESSAGE_ERROR, gtk.BUTTONS_OK,
                                  "Error opening %s: '%s'" % (file, err))
            d.run()
            d.destroy()
        
    def about(self,action,widget):
        print "about"

    def quit(self,action,widget=None):
        gtk.main_quit()

def main():
    mainWindow = MainWindow()
    gtk.main()
    
if __name__ == '__main__':
    main()
