// FractCtl.idl : IDL source for FractCtl.dll
//

// This file will be processed by the MIDL tool to
// produce the type library (FractCtl.tlb) and marshalling code.

import "oaidl.idl";
import "ocidl.idl";
#include "olectl.h"
	

	[
		object,
		uuid(FE90F085-1F2F-4368-AE72-4E8E4F3552D2),
		dual,
		helpstring("IFractal Interface"),
		pointer_default(unique)
	]
	interface IFractal : IDispatch
	{
	};

[
	uuid(6314BA1A-6ED9-4BE9-8AB7-A893685BC600),
	version(1.0),
	helpstring("FractCtl 1.0 Type Library")
]
library FRACTCTLLib
{
	importlib("stdole32.tlb");
	importlib("stdole2.tlb");

	[
		uuid(DBB7B74C-C462-4173-9EDA-7FFA5B261114),
		helpstring("_IFractalEvents Interface")
	]
	dispinterface _IFractalEvents
	{
		properties:
		methods:
	};

	[
		uuid(E6C5FD76-B0E0-4F56-B3C0-E4B263FEDE00),
		helpstring("Fractal Class")
	]
	coclass Fractal
	{
		[default] interface IFractal;
		[default, source] dispinterface _IFractalEvents;
	};
};
